spring.application.name=DSCatalog
spring.profiles.active=${APP_PROFILE:test}

# Fecha a sessão nas camadas de serviço e de acesso à dados
# Quando retornar a controllers já foi encerrada
# @transaciton ou @transaciton(readOnly = true)
spring.jpa.open-in-view=false